### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tibordp** [douglasmakey/admissioncontroller#1]
First of all thank you for writing this example, it has been very useful for writing my own admission controller.

I noticed that there is no license specified for this repo. Do you think it would be possible to provide one?

Thank you!

**Comment by douglasmakey** [comment]
Hi @tibordp 

Happy to hear that this is useful for you. Thanks for the suggestion, I already added the license.

**Comment by tibordp** [comment]
Thank you!

**Comment by BenjaminHerbert** [comment]
@douglasmakey Could you clarify this part of the license?
 
>    Copyright [yyyy] [name of copyright owner]

See: https://github.com/douglasmakey/admissioncontroller/blob/master/LICENSE#L189
